version: "2"

services:
  redis:
    container_name: redis
    image: docker.io/bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "~/docker/container/redis:/bitnami/redis/data"

volumes:
  redis_data:
    driver: local
